version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "3001"
      NEO4J_URI: ""
      NEO4J_USER: ""
      NEO4J_PASSWORD: ""
    ports:
      - "3001:3001"
    command: yarn start:dev
